import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1765077308219 implements MigrationInterface {
    name = 'InitSchema1765077308219'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "taxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(5) NOT NULL, "description" character varying(100) NOT NULL, "amount" numeric(9,2) NOT NULL, "taxId" uuid, CONSTRAINT "PK_6c58c9cbb420c4f65e3f5eb8162" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "identification_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "code" character varying(2) NOT NULL, "description" character varying(50) NOT NULL, CONSTRAINT "PK_2c5e774af32b420dafcc7bb3aab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('TRAVEL', 'SUPPLIES', 'UTILITIES', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "expenseDate" date NOT NULL, "description" character varying(100) NOT NULL, "amount" numeric(9,4) NOT NULL, "category" "public"."expenses_category_enum" NOT NULL, CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carrriers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "plateNumber" character varying(50) NOT NULL, "party_id" uuid, CONSTRAINT "PK_0bc42d894a7de82ed1ab1cd27c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."promotions_discounttype_enum" AS ENUM('percentage', 'fixed_amount')`);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "title" character varying(150) NOT NULL, "description" text, "discountType" "public"."promotions_discounttype_enum" NOT NULL, "discountValue" numeric(9,4) NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "code" character varying(10), "minimumPurchaseAmount" numeric(10,2), "usageLimit" integer, "perUserLimit" integer, "categoryId" uuid, CONSTRAINT "UQ_8ab10e580f70c3d2e2e4b31ebf2" UNIQUE ("code"), CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "description" character varying(100) NOT NULL, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(9,4) NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "purchase_id" uuid, "item_id" uuid, CONSTRAINT "PK_b0988b2c3f2e1e5d95756b01389" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchases_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "documentNro" character varying(20) NOT NULL, "totalPrice" numeric(9,4) NOT NULL, "totalZero" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "observations" character varying(100), "guiaNumber" character varying(20) NOT NULL, "status" "public"."purchases_status_enum" NOT NULL DEFAULT 'ACTIVE', "purchaseDate" date NOT NULL, CONSTRAINT "PK_1d55032f37a34c6eceacbbca6b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(9,4) NOT NULL, "purchase_id" uuid, "payment_method_id" uuid, CONSTRAINT "PK_9765d702e073d3cdf9b1600792d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(12,2) NOT NULL, "sale_id" uuid, "payment_method_id" uuid, CONSTRAINT "PK_1117d02608a00d131b95f60a58e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "code" character varying(2) NOT NULL, "description" character varying(100) NOT NULL, "status" "public"."payment_method_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_7744c2b2dd932c9cf42f2b9bc3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "debit_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "reason" character varying(255) NOT NULL, "issueDate" TIMESTAMP NOT NULL, "invoiceNumber" character varying(17) NOT NULL, "modifiedDocumentType" character varying(2) NOT NULL DEFAULT '01', "sale_id" uuid, "payment_method_id" uuid, CONSTRAINT "PK_e1f73e65add1542776ce7087fae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credit_note_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "descripcion" character varying(100) NOT NULL, "quantity" numeric(9,4) NOT NULL, "unitPrice" numeric NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "debit_note_id" uuid, "item_id" uuid, CONSTRAINT "PK_805bf3af6de5dce4b2b5db057ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "lotNumber" character varying(50) NOT NULL, "expirationDate" date NOT NULL, "stock" numeric(9,4) NOT NULL, "manufacturerCode" character varying, "item_id" uuid, CONSTRAINT "PK_2bb990a4015865cb1daa1d22fd9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "quantity" numeric(9,4) NOT NULL DEFAULT '0', "reserved" numeric(9,4) NOT NULL DEFAULT '0', "item_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b136c68f7478c3fa49229d6f57" ON "stock" ("item_id", "warehouse_id") `);
        await queryRunner.query(`CREATE TABLE "warehouse" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "warehouseName" character varying(200) NOT NULL, "location" character varying, CONSTRAINT "PK_965abf9f99ae8c5983ae74ebde8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movement_typemovement_enum" AS ENUM('IN', 'OUT', 'ADJUSTMENT', 'TRANSFER')`);
        await queryRunner.query(`CREATE TABLE "stock_movement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "dateMovement" date NOT NULL, "typeMovement" "public"."stock_movement_typemovement_enum" NOT NULL DEFAULT 'IN', "quantity" numeric(9,4) NOT NULL, "unitCost" numeric(9,4) NOT NULL, "balance" numeric(9,4) NOT NULL, "item_id" uuid, "reason_id" uuid, "warehouse_id" uuid, CONSTRAINT "PK_9fe1232f916686ae8cf00294749" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movement_reason" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "code" character varying(3) NOT NULL, "description" character varying(150) NOT NULL, "isForKardex" boolean NOT NULL DEFAULT true, "isForGuia" boolean NOT NULL DEFAULT true, "isForInventoryAdjustment" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_aeb76e8dd008167f44ce3baa3ec" UNIQUE ("code"), CONSTRAINT "PK_5dea308ed7982e29e18bc14e50f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "remission_guides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "issueDate" date NOT NULL, "invoiceNumber" character varying(17) NOT NULL, "authorizationNumber" character varying(49) NOT NULL, "arrivalPoint" character varying(255) NOT NULL, "departureDate" date NOT NULL, "arrivalDate" date NOT NULL, "destinationEstablishmentCode" character varying(3) NOT NULL, "customsCode" character varying(20) NOT NULL, "branchCode" character varying(3) NOT NULL, "sale_id" uuid, "purchase_id" uuid, "carrier_id" uuid, "warehouse_id" uuid, "movement_reason_id" uuid, CONSTRAINT "REL_b9fd3930c71019f8e356b0b231" UNIQUE ("sale_id"), CONSTRAINT "REL_2eaaa3a5a48d27ba880826fc50" UNIQUE ("purchase_id"), CONSTRAINT "REL_4b480729e659cc5db0e4998b40" UNIQUE ("carrier_id"), CONSTRAINT "PK_4e7dc83bf7b7d0b9c20373db6f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "remission_guide_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric NOT NULL DEFAULT '0', "weight" numeric NOT NULL DEFAULT '0', "remission_guide_id" uuid, "item_id" uuid, CONSTRAINT "PK_37140ac03a906613386c671fac6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(9,4) NOT NULL, "unitPrice" numeric(9,4) NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "sale_id" uuid, "ite_id" uuid, CONSTRAINT "PK_4a2e151a26169857b1f3d47c198" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unit_measurements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "description" character varying(50) NOT NULL, CONSTRAINT "PK_24da8c0261ebac9fd1ed2199744" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."items_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "barcode" character varying(20) NOT NULL, "itemName" character varying(150) NOT NULL, "description" character varying(300), "unitPrice" numeric(9,4) NOT NULL, "salePrice" numeric(9,4) NOT NULL, "hasIva" boolean NOT NULL, "controlStock" boolean NOT NULL DEFAULT false, "status" "public"."items_status_enum" NOT NULL DEFAULT 'ACTIVE', "category_id" uuid, "unit_measurement_id" uuid, CONSTRAINT "PK_ba5885359424c15ca6b9e79bcf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d4255d4e0810807dea55d9a406" ON "items" ("barcode") `);
        await queryRunner.query(`CREATE TABLE "purchase_liquidation_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(9,4) NOT NULL, "unitPrice" numeric(9,4) NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "purchase_liquidation_id" uuid, "item_id" uuid, CONSTRAINT "PK_fcd19271f76735d2be91b510877" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_liquidation_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "purchase_liquidation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "documentNumber" character varying(20) NOT NULL, "totalPrice" numeric(4,9) NOT NULL, "totalZero" numeric(4,9) NOT NULL, "tax" numeric(4,9) NOT NULL, "observations" numeric(4,9), "guiaNumber" character varying, "saleDate" date NOT NULL, "status" "public"."purchase_liquidation_status_enum" NOT NULL DEFAULT 'ACTIVE', "supplierId" uuid, CONSTRAINT "PK_e4c30f3bcd57b8e8cfb22e31c3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "withholding_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "withholding_id" uuid, CONSTRAINT "PK_40147250b1c0a6bb87c210f2d25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "withholdings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "month" integer NOT NULL, "year" integer NOT NULL, "taxableBase" numeric(9,2) NOT NULL DEFAULT '0', "percentage" numeric(9,2) NOT NULL DEFAULT '0', "withholdingPercentage" numeric(9,2) NOT NULL DEFAULT '0', "supplier_id" uuid, "tax_id" uuid, CONSTRAINT "REL_5d55147f054da31b8ca25caf2d" UNIQUE ("tax_id"), CONSTRAINT "PK_0bcd2ff7a68e52990649d3354b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "party_id" uuid, CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."parties_partytype_enum" AS ENUM('PERSON', 'COMPANY')`);
        await queryRunner.query(`CREATE TABLE "parties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partyType" "public"."parties_partytype_enum" NOT NULL DEFAULT 'PERSON', "identificationNumber" character varying(13) NOT NULL, "tradeName" character varying(250) NOT NULL, "companyName" character varying(250) NOT NULL, "address" character varying(150) NOT NULL, "email" character varying(100) NOT NULL, "phoneNumber" character varying(10), "accounting_obliged" boolean NOT NULL DEFAULT false, "special_contributor" boolean NOT NULL DEFAULT false, "special_code" character varying(20), CONSTRAINT "UQ_5017d1d5544f70d5e1d0addc1e6" UNIQUE ("identificationNumber"), CONSTRAINT "PK_da698299dca60d55f0050dde935" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "creditLimit" numeric(9,2) NOT NULL DEFAULT '0', "party_id" uuid, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "documentNumber" character varying(20) NOT NULL, "totalPrice" numeric(4,9) NOT NULL, "totalZero" numeric(4,9) NOT NULL, "tax" numeric(4,9) NOT NULL, "observations" numeric(4,9), "guiaNumber" character varying, "saleDate" date NOT NULL, "status" "public"."sales_status_enum" NOT NULL DEFAULT 'ACTIVE', "customer_id" uuid, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."credit_notes_reason_enum" AS ENUM('DEVOLUCION', 'DESCUENTO', 'BONIFICACION', 'ANULACION', 'OTROS')`);
        await queryRunner.query(`CREATE TABLE "credit_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "issueDate" date NOT NULL, "invoiceNumber" character varying(17) NOT NULL, "modifiedDocumentType" character varying(2) NOT NULL DEFAULT '01', "reason" "public"."credit_notes_reason_enum" NOT NULL, "sale_id" uuid, CONSTRAINT "PK_4933888a20b5469e119ad74b9e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credit_note_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(9,4) NOT NULL, "description" character varying(300) NOT NULL, "unitPrice" numeric(9,4) NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "credit_note_id" uuid, "item_id" uuid, CONSTRAINT "PK_b7e8cf701ab157da0996344a1e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sequence" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "establishment" character varying(3) NOT NULL, "emissionPoint" character varying(3) NOT NULL, "nextNumber" integer NOT NULL DEFAULT '1', "prefix" character varying(1) NOT NULL, "document_type_id" uuid, CONSTRAINT "PK_775d7d43700407de90b5f0d7584" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "code" character varying(2) NOT NULL, "documentName" character varying(100) NOT NULL, "withholdingApply" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d467d7eeb7c8ce216e90e8494aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."electronic_documents_status_enum" AS ENUM('SIGNED', 'SENT', 'AUTHORIZED', 'REJECTED', 'ANNULLED', 'REICIVED')`);
        await queryRunner.query(`CREATE TABLE "electronic_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "accessKey" character varying(49) NOT NULL, "authorizationNumber" character varying(49) NOT NULL, "authorizationDate" TIMESTAMP, "signedXml" text, "authorizedXml" text, "status" "public"."electronic_documents_status_enum" NOT NULL DEFAULT 'SIGNED', "document_type_id" uuid, "sale_id" uuid, "guide_id" uuid, "credit_note_id" uuid, "debit_note_id" uuid, "purchase_liquidation_id" uuid, "withholding_id" uuid, CONSTRAINT "REL_8f26632d75be35098ba8672c34" UNIQUE ("sale_id"), CONSTRAINT "REL_f1af70ebdaf5d576607d811810" UNIQUE ("guide_id"), CONSTRAINT "REL_09296d4cf076c49709b12418bb" UNIQUE ("credit_note_id"), CONSTRAINT "REL_f922457f05c83d5552d194407c" UNIQUE ("debit_note_id"), CONSTRAINT "REL_00e32caeb025b72c8637e20fdd" UNIQUE ("purchase_liquidation_id"), CONSTRAINT "REL_bd5b8a63dd71e39b1721b336c4" UNIQUE ("withholding_id"), CONSTRAINT "CHK_c8ad158ea0dbe6ecb514b08ebe" CHECK (
      ((sale_id IS NOT NULL)::int +
      (guide_id IS NOT NULL)::int +
      (credit_note_id IS NOT NULL)::int +
      (debit_note_id IS NOT NULL)::int +
      (purchase_liquidation_id IS NOT NULL)::int +
      (withholding_id IS NOT NULL)::int) = 1
    ), CONSTRAINT "PK_a1f3ca18013342f3867966b485d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."certificate_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "certificate" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "fileName" text NOT NULL, "fileKey" text NOT NULL, "filePath" text NOT NULL, "encryptedP12" bytea, "thumbprint" text, "validFrom" date NOT NULL, "validTo" date NOT NULL, "status" "public"."certificate_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_8daddfc65f59e341c2bbc9c9e43" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roleName" character varying(100) NOT NULL, "description" character varying, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(150) NOT NULL, "username" character varying(50) NOT NULL, "passwordHash" character varying(200) NOT NULL, "active" boolean NOT NULL DEFAULT true, "lastLogin" TIMESTAMP WITH TIME ZONE, "tenant_id" uuid NOT NULL, "role_id" uuid, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f4c2efab52114c4e99e28efb" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE TYPE "public"."tenants_srienvironment_enum" AS ENUM('TESTING', 'PRODUCTION')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "logoUrl" text, "sriEnvironment" "public"."tenants_srienvironment_enum" NOT NULL DEFAULT 'TESTING', "isActive" boolean NOT NULL DEFAULT true, "config" jsonb, "party_id" uuid, "certificate_id" uuid, CONSTRAINT "REL_451f765bbe21478e9ccb6aa4bd" UNIQUE ("party_id"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_suppliers" ("itemId" uuid NOT NULL, "supplier_id" uuid NOT NULL, CONSTRAINT "PK_985c392467b25f571b38f8ec31a" PRIMARY KEY ("itemId", "supplier_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2f7b545014da4e5ac38c373c3" ON "item_suppliers" ("itemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2365014fdeb4fd16cf9504178" ON "item_suppliers" ("supplier_id") `);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "taxId"`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "taxId" uuid`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "tenant_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "created_by" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "updated_by" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "isRetencion" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD CONSTRAINT "FK_945731221d16503edfa5aacb7a5" FOREIGN KEY ("taxId") REFERENCES "taxes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrriers" ADD CONSTRAINT "FK_f873fef3a0b7c1bd45caa7e6bbb" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_4a454934d715cd3ca29ab675349" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" ADD CONSTRAINT "FK_28f8b3d42bcff4501d7a60c61d8" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" ADD CONSTRAINT "FK_726bcabc0c1a24e4c1106c0ed83" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_b0089820b7452d8e84b5d1fda65" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_8a7167ed862a0600ae36cc0917c" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_9c7db4fd07371a0c1eddcd1bd20" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "debit_notes" ADD CONSTRAINT "FK_58f0559f303763439b0bf01a6b3" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "debit_notes" ADD CONSTRAINT "FK_2c1dea9ca0801e44684b492d616" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_note_detail" ADD CONSTRAINT "FK_88fc0521bd65aa63f5d51e3fa9f" FOREIGN KEY ("debit_note_id") REFERENCES "debit_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_note_detail" ADD CONSTRAINT "FK_0f178542315b907244cddeff7d7" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lots" ADD CONSTRAINT "FK_23237dbb26386b3ee0c0cafe4c8" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_0b51047279d22d97442d46dfee8" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_b2be25bd3e78455fe801c45e892" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movement" ADD CONSTRAINT "FK_2222849c36f2c923a4fdd19b1a8" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movement" ADD CONSTRAINT "FK_f47845a896a34a9e989ea46006a" FOREIGN KEY ("reason_id") REFERENCES "movement_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movement" ADD CONSTRAINT "FK_84dea70c36df8700e616018f256" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_b9fd3930c71019f8e356b0b2316" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_2eaaa3a5a48d27ba880826fc509" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_4b480729e659cc5db0e4998b405" FOREIGN KEY ("carrier_id") REFERENCES "carrriers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_f97f75b391c6d21748430e3adbe" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_dfcfb839bfb86f87995cd7a53ce" FOREIGN KEY ("movement_reason_id") REFERENCES "movement_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guide_detail" ADD CONSTRAINT "FK_6789081fb6922aa29289e1871d6" FOREIGN KEY ("remission_guide_id") REFERENCES "remission_guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guide_detail" ADD CONSTRAINT "FK_637fa2457bd1fc924e22c422a42" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_f51acf047cb9b82ea8b0508f95a" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_a8245e923a0403ef58224a91e48" FOREIGN KEY ("ite_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_0c4aa809ddf5b0c6ca45d8a8e80" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_41612ad71ba48392ba7977103d1" FOREIGN KEY ("unit_measurement_id") REFERENCES "unit_measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation_detail" ADD CONSTRAINT "FK_2e22564083589c7cc4c7e5ae262" FOREIGN KEY ("purchase_liquidation_id") REFERENCES "purchase_liquidation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation_detail" ADD CONSTRAINT "FK_1ea96aa352ff937b521a23735a4" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation" ADD CONSTRAINT "FK_7965bb1da8349336a67f2f38630" FOREIGN KEY ("supplierId") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withholding_details" ADD CONSTRAINT "FK_c1edd39312aca7a5ff8a8eae4dc" FOREIGN KEY ("withholding_id") REFERENCES "withholdings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withholdings" ADD CONSTRAINT "FK_4057831c1e2230094debcd8184d" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withholdings" ADD CONSTRAINT "FK_5d55147f054da31b8ca25caf2dc" FOREIGN KEY ("tax_id") REFERENCES "taxes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_1c944701a896e794276f43769a2" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_a68cab09a94768788280c3cbf0b" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_notes" ADD CONSTRAINT "FK_3b00782ddf92177eced19a05973" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_note_details" ADD CONSTRAINT "FK_2ed159ea81d2d2186c50bba8835" FOREIGN KEY ("credit_note_id") REFERENCES "credit_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_note_details" ADD CONSTRAINT "FK_fad0050b1a873a4538cae0f8fcc" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sequence" ADD CONSTRAINT "FK_ddcd02f607407333daf39eae55b" FOREIGN KEY ("document_type_id") REFERENCES "document_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_890c73d7da6439aaa032cd10b9d" FOREIGN KEY ("document_type_id") REFERENCES "document_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_8f26632d75be35098ba8672c34e" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_f1af70ebdaf5d576607d811810a" FOREIGN KEY ("guide_id") REFERENCES "remission_guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_09296d4cf076c49709b12418bb3" FOREIGN KEY ("credit_note_id") REFERENCES "credit_notes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_f922457f05c83d5552d194407cb" FOREIGN KEY ("debit_note_id") REFERENCES "debit_notes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_00e32caeb025b72c8637e20fdda" FOREIGN KEY ("purchase_liquidation_id") REFERENCES "purchase_liquidation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_bd5b8a63dd71e39b1721b336c43" FOREIGN KEY ("withholding_id") REFERENCES "withholdings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_451f765bbe21478e9ccb6aa4bdd" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_9a49161a1f88b533b7da44e4ba6" FOREIGN KEY ("certificate_id") REFERENCES "certificate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_suppliers" ADD CONSTRAINT "FK_d2f7b545014da4e5ac38c373c32" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_suppliers" ADD CONSTRAINT "FK_e2365014fdeb4fd16cf9504178d" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_suppliers" DROP CONSTRAINT "FK_e2365014fdeb4fd16cf9504178d"`);
        await queryRunner.query(`ALTER TABLE "item_suppliers" DROP CONSTRAINT "FK_d2f7b545014da4e5ac38c373c32"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_9a49161a1f88b533b7da44e4ba6"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_451f765bbe21478e9ccb6aa4bdd"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_bd5b8a63dd71e39b1721b336c43"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_00e32caeb025b72c8637e20fdda"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_f922457f05c83d5552d194407cb"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_09296d4cf076c49709b12418bb3"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_f1af70ebdaf5d576607d811810a"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_8f26632d75be35098ba8672c34e"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_890c73d7da6439aaa032cd10b9d"`);
        await queryRunner.query(`ALTER TABLE "sequence" DROP CONSTRAINT "FK_ddcd02f607407333daf39eae55b"`);
        await queryRunner.query(`ALTER TABLE "credit_note_details" DROP CONSTRAINT "FK_fad0050b1a873a4538cae0f8fcc"`);
        await queryRunner.query(`ALTER TABLE "credit_note_details" DROP CONSTRAINT "FK_2ed159ea81d2d2186c50bba8835"`);
        await queryRunner.query(`ALTER TABLE "credit_notes" DROP CONSTRAINT "FK_3b00782ddf92177eced19a05973"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_a68cab09a94768788280c3cbf0b"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_1c944701a896e794276f43769a2"`);
        await queryRunner.query(`ALTER TABLE "withholdings" DROP CONSTRAINT "FK_5d55147f054da31b8ca25caf2dc"`);
        await queryRunner.query(`ALTER TABLE "withholdings" DROP CONSTRAINT "FK_4057831c1e2230094debcd8184d"`);
        await queryRunner.query(`ALTER TABLE "withholding_details" DROP CONSTRAINT "FK_c1edd39312aca7a5ff8a8eae4dc"`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation" DROP CONSTRAINT "FK_7965bb1da8349336a67f2f38630"`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation_detail" DROP CONSTRAINT "FK_1ea96aa352ff937b521a23735a4"`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation_detail" DROP CONSTRAINT "FK_2e22564083589c7cc4c7e5ae262"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_41612ad71ba48392ba7977103d1"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_0c4aa809ddf5b0c6ca45d8a8e80"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_a8245e923a0403ef58224a91e48"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_f51acf047cb9b82ea8b0508f95a"`);
        await queryRunner.query(`ALTER TABLE "remission_guide_detail" DROP CONSTRAINT "FK_637fa2457bd1fc924e22c422a42"`);
        await queryRunner.query(`ALTER TABLE "remission_guide_detail" DROP CONSTRAINT "FK_6789081fb6922aa29289e1871d6"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_dfcfb839bfb86f87995cd7a53ce"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_f97f75b391c6d21748430e3adbe"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_4b480729e659cc5db0e4998b405"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_2eaaa3a5a48d27ba880826fc509"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_b9fd3930c71019f8e356b0b2316"`);
        await queryRunner.query(`ALTER TABLE "stock_movement" DROP CONSTRAINT "FK_84dea70c36df8700e616018f256"`);
        await queryRunner.query(`ALTER TABLE "stock_movement" DROP CONSTRAINT "FK_f47845a896a34a9e989ea46006a"`);
        await queryRunner.query(`ALTER TABLE "stock_movement" DROP CONSTRAINT "FK_2222849c36f2c923a4fdd19b1a8"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_b2be25bd3e78455fe801c45e892"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_0b51047279d22d97442d46dfee8"`);
        await queryRunner.query(`ALTER TABLE "lots" DROP CONSTRAINT "FK_23237dbb26386b3ee0c0cafe4c8"`);
        await queryRunner.query(`ALTER TABLE "credit_note_detail" DROP CONSTRAINT "FK_0f178542315b907244cddeff7d7"`);
        await queryRunner.query(`ALTER TABLE "credit_note_detail" DROP CONSTRAINT "FK_88fc0521bd65aa63f5d51e3fa9f"`);
        await queryRunner.query(`ALTER TABLE "debit_notes" DROP CONSTRAINT "FK_2c1dea9ca0801e44684b492d616"`);
        await queryRunner.query(`ALTER TABLE "debit_notes" DROP CONSTRAINT "FK_58f0559f303763439b0bf01a6b3"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_9c7db4fd07371a0c1eddcd1bd20"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_8a7167ed862a0600ae36cc0917c"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_b0089820b7452d8e84b5d1fda65"`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" DROP CONSTRAINT "FK_726bcabc0c1a24e4c1106c0ed83"`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" DROP CONSTRAINT "FK_28f8b3d42bcff4501d7a60c61d8"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_4a454934d715cd3ca29ab675349"`);
        await queryRunner.query(`ALTER TABLE "carrriers" DROP CONSTRAINT "FK_f873fef3a0b7c1bd45caa7e6bbb"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP CONSTRAINT "FK_945731221d16503edfa5aacb7a5"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "isRetencion"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "tenant_id"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP COLUMN "taxId"`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD "taxId" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2365014fdeb4fd16cf9504178"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2f7b545014da4e5ac38c373c3"`);
        await queryRunner.query(`DROP TABLE "item_suppliers"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_srienvironment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f4c2efab52114c4e99e28efb"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "certificate"`);
        await queryRunner.query(`DROP TYPE "public"."certificate_status_enum"`);
        await queryRunner.query(`DROP TABLE "electronic_documents"`);
        await queryRunner.query(`DROP TYPE "public"."electronic_documents_status_enum"`);
        await queryRunner.query(`DROP TABLE "document_types"`);
        await queryRunner.query(`DROP TABLE "sequence"`);
        await queryRunner.query(`DROP TABLE "credit_note_details"`);
        await queryRunner.query(`DROP TABLE "credit_notes"`);
        await queryRunner.query(`DROP TYPE "public"."credit_notes_reason_enum"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "parties"`);
        await queryRunner.query(`DROP TYPE "public"."parties_partytype_enum"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "withholdings"`);
        await queryRunner.query(`DROP TABLE "withholding_details"`);
        await queryRunner.query(`DROP TABLE "purchase_liquidation"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_liquidation_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_liquidation_detail"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4255d4e0810807dea55d9a406"`);
        await queryRunner.query(`DROP TABLE "items"`);
        await queryRunner.query(`DROP TYPE "public"."items_status_enum"`);
        await queryRunner.query(`DROP TABLE "unit_measurements"`);
        await queryRunner.query(`DROP TABLE "sale_detail"`);
        await queryRunner.query(`DROP TABLE "remission_guide_detail"`);
        await queryRunner.query(`DROP TABLE "remission_guides"`);
        await queryRunner.query(`DROP TABLE "movement_reason"`);
        await queryRunner.query(`DROP TABLE "stock_movement"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movement_typemovement_enum"`);
        await queryRunner.query(`DROP TABLE "warehouse"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b136c68f7478c3fa49229d6f57"`);
        await queryRunner.query(`DROP TABLE "stock"`);
        await queryRunner.query(`DROP TABLE "lots"`);
        await queryRunner.query(`DROP TABLE "credit_note_detail"`);
        await queryRunner.query(`DROP TABLE "debit_notes"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_status_enum"`);
        await queryRunner.query(`DROP TABLE "sale_payments"`);
        await queryRunner.query(`DROP TABLE "purchase_payments"`);
        await queryRunner.query(`DROP TABLE "purchases"`);
        await queryRunner.query(`DROP TYPE "public"."purchases_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_detail"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP TYPE "public"."promotions_discounttype_enum"`);
        await queryRunner.query(`DROP TABLE "carrriers"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`DROP TABLE "identification_type"`);
        await queryRunner.query(`DROP TABLE "taxes"`);
    }

}
