import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1766463432537 implements MigrationInterface {
    name = 'InitSchema1766463432537'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "withholding_type_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(5) NOT NULL, "description" character varying(20) NOT NULL, "percentage" numeric(9,2) NOT NULL, "withholdingTypeId" uuid, CONSTRAINT "PK_fd506a5a382582c650be67c6a31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "withholding_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(5) NOT NULL, "description" character varying(100) NOT NULL, "isActive" boolean NOT NULL, CONSTRAINT "PK_26bda9bb9edeb50a47f2397337e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "detail_tax_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(5) NOT NULL, "description" character varying(100) NOT NULL, "percentage" numeric(9,2) NOT NULL, "taxId" uuid, CONSTRAINT "PK_9b1e31fd532a174d914643148ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "type_taxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(5) NOT NULL, "description" character varying(100) NOT NULL, "isActive" boolean NOT NULL, CONSTRAINT "PK_00d7a0b2d8e44fa4e41e3aa6760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_taxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "tax_id" uuid, CONSTRAINT "PK_d07f724628b6dc2c4bc5355ab25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_29ad220fc1e33ebfb74c64a9d1" ON "tenant_taxes" ("tenant_id", "tax_id") `);
        await queryRunner.query(`CREATE TABLE "identification_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(2) NOT NULL, "description" character varying(50) NOT NULL, CONSTRAINT "PK_2c5e774af32b420dafcc7bb3aab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credit_note_reason" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(5), "description" character varying(100) NOT NULL, "isActive" boolean NOT NULL, CONSTRAINT "PK_b554dea0f1d093e0b4c309d4161" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('TRAVEL', 'SUPPLIES', 'UTILITIES', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "expenseDate" date NOT NULL, "description" character varying(100) NOT NULL, "amount" numeric(9,4) NOT NULL, "category" "public"."expenses_category_enum" NOT NULL, CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."promotions_discounttype_enum" AS ENUM('percentage', 'fixed_amount')`);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "title" character varying(150) NOT NULL, "description" text, "discountType" "public"."promotions_discounttype_enum" NOT NULL, "discountValue" numeric(9,4) NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "code" character varying(10), "minimumPurchaseAmount" numeric(10,2), "usageLimit" integer, "perUserLimit" integer, "categoryId" uuid, CONSTRAINT "UQ_8ab10e580f70c3d2e2e4b31ebf2" UNIQUE ("code"), CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "description" character varying(100) NOT NULL, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carriers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "plateNumber" character varying(50) NOT NULL, "party_id" uuid, CONSTRAINT "PK_fe886e72b3d9f67da3ce70f4368" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."parties_partytype_enum" AS ENUM('PERSON', 'COMPANY')`);
        await queryRunner.query(`CREATE TABLE "parties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partyType" "public"."parties_partytype_enum" NOT NULL DEFAULT 'PERSON', "identificationNumber" character varying(13) NOT NULL, "tradeName" character varying(250) NOT NULL, "companyName" character varying(250) NOT NULL, "address" character varying(150) NOT NULL, "email" character varying(100) NOT NULL, "phoneNumber" character varying(10), "accounting_obliged" boolean NOT NULL DEFAULT false, "special_contributor" boolean NOT NULL DEFAULT false, "special_code" character varying(20), CONSTRAINT "UQ_5017d1d5544f70d5e1d0addc1e6" UNIQUE ("identificationNumber"), CONSTRAINT "PK_da698299dca60d55f0050dde935" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "creditLimit" numeric(9,2) NOT NULL DEFAULT '0', "party_id" uuid, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "debit_note_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "descripcion" character varying(100) NOT NULL, "quantity" numeric(9,4) NOT NULL, "unitPrice" numeric NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "debit_note_id" uuid, "item_id" uuid, CONSTRAINT "PK_e73d8abbe1b9cece43b35e480c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(9,4) NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "purchase_id" uuid, "item_id" uuid, CONSTRAINT "PK_b0988b2c3f2e1e5d95756b01389" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchases_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "documentNro" character varying(20) NOT NULL, "totalPrice" numeric(9,4) NOT NULL, "totalZero" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "observations" character varying(100), "guiaNumber" character varying(20) NOT NULL, "status" "public"."purchases_status_enum" NOT NULL DEFAULT 'ACTIVE', "purchaseDate" date NOT NULL, CONSTRAINT "PK_1d55032f37a34c6eceacbbca6b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(9,4) NOT NULL, "purchase_id" uuid, "payment_method_id" uuid, CONSTRAINT "PK_9765d702e073d3cdf9b1600792d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(12,2) NOT NULL, "sale_id" uuid, "payment_method_id" uuid, CONSTRAINT "PK_1117d02608a00d131b95f60a58e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(2) NOT NULL, "description" character varying(100) NOT NULL, "status" "public"."payment_method_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_7744c2b2dd932c9cf42f2b9bc3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "debit_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "reason" character varying(255) NOT NULL, "issueDate" TIMESTAMP NOT NULL, "invoiceNumber" character varying(17) NOT NULL, "modifiedDocumentType" character varying(2) NOT NULL DEFAULT '01', "sale_id" uuid, "payment_method_id" uuid, CONSTRAINT "PK_e1f73e65add1542776ce7087fae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(9,4) NOT NULL, "unitPrice" numeric(9,4) NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "sale_id" uuid, "ite_id" uuid, CONSTRAINT "PK_4a2e151a26169857b1f3d47c198" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "documentNumber" character varying(20) NOT NULL, "totalPrice" numeric(4,9) NOT NULL, "totalZero" numeric(4,9) NOT NULL, "tax" numeric(4,9) NOT NULL, "observations" numeric(4,9), "guiaNumber" character varying, "saleDate" date NOT NULL, "status" "public"."sales_status_enum" NOT NULL DEFAULT 'ACTIVE', "customer_id" uuid, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credit_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "issueDate" date NOT NULL, "invoiceNumber" character varying(17) NOT NULL, "modifiedDocumentType" character varying(2) NOT NULL DEFAULT '01', "credit_note_reason_id" uuid, "sale_id" uuid, CONSTRAINT "REL_421ef876a7292a03a6e8dd9128" UNIQUE ("credit_note_reason_id"), CONSTRAINT "PK_4933888a20b5469e119ad74b9e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credit_note_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(9,4) NOT NULL, "description" character varying(300) NOT NULL, "unitPrice" numeric(9,4) NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "credit_note_id" uuid, "item_id" uuid, CONSTRAINT "PK_b7e8cf701ab157da0996344a1e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "lotNumber" character varying(50) NOT NULL, "expirationDate" date NOT NULL, "stock" numeric(9,4) NOT NULL, "manufacturerCode" character varying, "item_id" uuid, CONSTRAINT "PK_2bb990a4015865cb1daa1d22fd9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "quantity" numeric(9,4) NOT NULL DEFAULT '0', "reserved" numeric(9,4) NOT NULL DEFAULT '0', "item_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b136c68f7478c3fa49229d6f57" ON "stock" ("item_id", "warehouse_id") `);
        await queryRunner.query(`CREATE TABLE "warehouse" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "warehouseName" character varying(200) NOT NULL, "location" character varying, "isMain" boolean NOT NULL, "isActive" boolean NOT NULL, CONSTRAINT "PK_965abf9f99ae8c5983ae74ebde8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movement_typemovement_enum" AS ENUM('IN', 'OUT', 'ADJUSTMENT', 'TRANSFER')`);
        await queryRunner.query(`CREATE TABLE "stock_movement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "dateMovement" date NOT NULL, "typeMovement" "public"."stock_movement_typemovement_enum" NOT NULL DEFAULT 'IN', "quantity" numeric(9,4) NOT NULL, "unitCost" numeric(9,4) NOT NULL, "balance" numeric(9,4) NOT NULL, "item_id" uuid, "reason_id" uuid, "warehouse_id" uuid, CONSTRAINT "PK_9fe1232f916686ae8cf00294749" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movement_reason" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(3) NOT NULL, "description" character varying(150) NOT NULL, "isForKardex" boolean NOT NULL DEFAULT true, "isForGuia" boolean NOT NULL DEFAULT true, "isForInventoryAdjustment" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_aeb76e8dd008167f44ce3baa3ec" UNIQUE ("code"), CONSTRAINT "PK_5dea308ed7982e29e18bc14e50f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "remission_guides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "issueDate" date NOT NULL, "invoiceNumber" character varying(17) NOT NULL, "authorizationNumber" character varying(49) NOT NULL, "arrivalPoint" character varying(255) NOT NULL, "departureDate" date NOT NULL, "arrivalDate" date NOT NULL, "destinationEstablishmentCode" character varying(3) NOT NULL, "customsCode" character varying(20) NOT NULL, "branchCode" character varying(3) NOT NULL, "sale_id" uuid, "purchase_id" uuid, "carrier_id" uuid, "warehouse_id" uuid, "movement_reason_id" uuid, CONSTRAINT "REL_b9fd3930c71019f8e356b0b231" UNIQUE ("sale_id"), CONSTRAINT "REL_2eaaa3a5a48d27ba880826fc50" UNIQUE ("purchase_id"), CONSTRAINT "REL_4b480729e659cc5db0e4998b40" UNIQUE ("carrier_id"), CONSTRAINT "PK_4e7dc83bf7b7d0b9c20373db6f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "remission_guide_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric NOT NULL DEFAULT '0', "weight" numeric NOT NULL DEFAULT '0', "remission_guide_id" uuid, "item_id" uuid, CONSTRAINT "PK_37140ac03a906613386c671fac6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."unit_measurements_type_enum" AS ENUM('UNIT', 'WEIGHT', 'VOLUME', 'LENGTH', 'AREA', 'TIME', 'SERVICE')`);
        await queryRunner.query(`CREATE TABLE "unit_measurements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(5) NOT NULL, "description" character varying(50) NOT NULL, "type" "public"."unit_measurements_type_enum" NOT NULL, "isBase" boolean NOT NULL DEFAULT false, "symbol" character varying(10), "isActive" boolean NOT NULL DEFAULT true, "conversion_factor" numeric(14,6), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "base_unit_id" uuid, CONSTRAINT "PK_24da8c0261ebac9fd1ed2199744" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_93cf3893f0dd45999755aef505" ON "unit_measurements" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."items_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "barcode" character varying(20) NOT NULL, "itemName" character varying(150) NOT NULL, "description" character varying(300), "unitPrice" numeric(9,4) NOT NULL, "salePrice" numeric(9,4) NOT NULL, "hasIva" boolean NOT NULL, "ice" numeric(9,2) NOT NULL, "irbpnr" numeric(9,2) NOT NULL, "controlStock" boolean NOT NULL DEFAULT false, "status" "public"."items_status_enum" NOT NULL DEFAULT 'ACTIVE', "category_id" uuid, "unit_measurement_id" uuid, CONSTRAINT "PK_ba5885359424c15ca6b9e79bcf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d4255d4e0810807dea55d9a406" ON "items" ("barcode") `);
        await queryRunner.query(`CREATE TABLE "purchase_liquidation_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(9,4) NOT NULL, "unitPrice" numeric(9,4) NOT NULL, "discount" numeric(9,4) NOT NULL, "tax" numeric(9,4) NOT NULL, "purchase_liquidation_id" uuid, "item_id" uuid, CONSTRAINT "PK_fcd19271f76735d2be91b510877" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_liquidation_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "purchase_liquidation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "documentNumber" character varying(20) NOT NULL, "totalPrice" numeric(4,9) NOT NULL, "totalZero" numeric(4,9) NOT NULL, "tax" numeric(4,9) NOT NULL, "observations" numeric(4,9), "guiaNumber" character varying, "saleDate" date NOT NULL, "status" "public"."purchase_liquidation_status_enum" NOT NULL DEFAULT 'ACTIVE', "supplierId" uuid, CONSTRAINT "PK_e4c30f3bcd57b8e8cfb22e31c3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "withholding_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "withholding_id" uuid, CONSTRAINT "PK_40147250b1c0a6bb87c210f2d25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "withholdings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "month" integer NOT NULL, "year" integer NOT NULL, "taxableBase" numeric(9,2) NOT NULL DEFAULT '0', "percentage" numeric(9,2) NOT NULL DEFAULT '0', "withholdingPercentage" numeric(9,2) NOT NULL DEFAULT '0', "supplier_id" uuid, "tax_id" uuid, CONSTRAINT "REL_5d55147f054da31b8ca25caf2d" UNIQUE ("tax_id"), CONSTRAINT "PK_0bcd2ff7a68e52990649d3354b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "party_id" uuid, CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_unit_measurements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "unit_measurement_id" uuid NOT NULL, CONSTRAINT "PK_cb4f8ebb40729ddaa1a8bfae94c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6eb547f7f7b581208a300c5536" ON "tenant_unit_measurements" ("tenant_id", "unit_measurement_id") `);
        await queryRunner.query(`CREATE TYPE "public"."certificate_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "certificate" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "fileName" text NOT NULL, "fileKey" text NOT NULL, "filePath" text NOT NULL, "encryptedP12" bytea, "thumbprint" text, "validFrom" date NOT NULL, "validTo" date NOT NULL, "status" "public"."certificate_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_8daddfc65f59e341c2bbc9c9e43" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roleName" character varying(100) NOT NULL, "description" character varying, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(50) NOT NULL, "username" character varying(50) NOT NULL, "passwordHash" character varying(200) NOT NULL, "active" boolean NOT NULL DEFAULT true, "lastLogin" TIMESTAMP WITH TIME ZONE, "tenant_id" uuid NOT NULL, "role_id" uuid, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f4c2efab52114c4e99e28efb" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE TYPE "public"."tenants_srienvironment_enum" AS ENUM('TESTING', 'PRODUCTION')`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_businesstype_enum" AS ENUM('COMMERCE', 'SERVICES', 'CONSTRUCTION')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "logoUrl" text, "sriEnvironment" "public"."tenants_srienvironment_enum" NOT NULL DEFAULT 'TESTING', "businessType" "public"."tenants_businesstype_enum" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "config" jsonb, "party_id" uuid, CONSTRAINT "REL_451f765bbe21478e9ccb6aa4bd" UNIQUE ("party_id"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tenant_establishments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "code" character varying(3) NOT NULL, "name" character varying(150) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_15de6621fc3f6970337185540d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9a4531cdccd770ff57c91cd8af" ON "tenant_establishments" ("tenant_id", "code") `);
        await queryRunner.query(`CREATE TABLE "tenant_emission_points" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(3) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "establishment_id" uuid, CONSTRAINT "PK_50f2a5385d393f389df6f7bbae1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1545e37cd662f59dde1b762251" ON "tenant_emission_points" ("establishment_id", "code") `);
        await queryRunner.query(`CREATE TABLE "tenant_numbering" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "nextNumber" integer NOT NULL DEFAULT '1', "prefix" character varying(1), "establishment_id" uuid, "emission_point_id" uuid, "document_type_id" uuid, CONSTRAINT "PK_f92fb00d95d9570d627f373aab4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_39457c1f4ecc7e8db88da581b7" ON "tenant_numbering" ("tenant_id", "document_type_id", "establishment_id", "emission_point_id") `);
        await queryRunner.query(`CREATE TABLE "document_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(2) NOT NULL, "documentName" character varying(100) NOT NULL, "withholdingApply" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d467d7eeb7c8ce216e90e8494aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."electronic_documents_status_enum" AS ENUM('EN PROCESO', 'NO AUTORIZADO', 'AUTORIZADO')`);
        await queryRunner.query(`CREATE TABLE "electronic_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying(150), "updated_by" character varying(150), "accessKey" character varying(49) NOT NULL, "authorizationNumber" character varying(49) NOT NULL, "authorizationDate" TIMESTAMP, "signedXml" text, "authorizedXml" text, "status" "public"."electronic_documents_status_enum" NOT NULL DEFAULT 'EN PROCESO', "document_type_id" uuid, "sale_id" uuid, "guide_id" uuid, "credit_note_id" uuid, "debit_note_id" uuid, "purchase_liquidation_id" uuid, "withholding_id" uuid, CONSTRAINT "REL_8f26632d75be35098ba8672c34" UNIQUE ("sale_id"), CONSTRAINT "REL_f1af70ebdaf5d576607d811810" UNIQUE ("guide_id"), CONSTRAINT "REL_09296d4cf076c49709b12418bb" UNIQUE ("credit_note_id"), CONSTRAINT "REL_f922457f05c83d5552d194407c" UNIQUE ("debit_note_id"), CONSTRAINT "REL_00e32caeb025b72c8637e20fdd" UNIQUE ("purchase_liquidation_id"), CONSTRAINT "REL_bd5b8a63dd71e39b1721b336c4" UNIQUE ("withholding_id"), CONSTRAINT "CHK_c8ad158ea0dbe6ecb514b08ebe" CHECK (
      ((sale_id IS NOT NULL)::int +
      (guide_id IS NOT NULL)::int +
      (credit_note_id IS NOT NULL)::int +
      (debit_note_id IS NOT NULL)::int +
      (purchase_liquidation_id IS NOT NULL)::int +
      (withholding_id IS NOT NULL)::int) = 1
    ), CONSTRAINT "PK_a1f3ca18013342f3867966b485d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_suppliers" ("itemId" uuid NOT NULL, "supplier_id" uuid NOT NULL, CONSTRAINT "PK_985c392467b25f571b38f8ec31a" PRIMARY KEY ("itemId", "supplier_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2f7b545014da4e5ac38c373c3" ON "item_suppliers" ("itemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2365014fdeb4fd16cf9504178" ON "item_suppliers" ("supplier_id") `);
        await queryRunner.query(`ALTER TABLE "withholding_type_detail" ADD CONSTRAINT "FK_f29f81f93481a3f096271f1e61d" FOREIGN KEY ("withholdingTypeId") REFERENCES "withholding_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detail_tax_type" ADD CONSTRAINT "FK_af31f447f3c4a3bd2f908526276" FOREIGN KEY ("taxId") REFERENCES "type_taxes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_taxes" ADD CONSTRAINT "FK_e555e263926898df594e1f5ffa6" FOREIGN KEY ("tax_id") REFERENCES "type_taxes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_4a454934d715cd3ca29ab675349" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carriers" ADD CONSTRAINT "FK_118b02bcf80db8eb5d7982ecd67" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_a68cab09a94768788280c3cbf0b" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "debit_note_detail" ADD CONSTRAINT "FK_4898dbed96c8d7c4da010d706ea" FOREIGN KEY ("debit_note_id") REFERENCES "debit_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "debit_note_detail" ADD CONSTRAINT "FK_a1af95ca14225263f1f4c7fe280" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" ADD CONSTRAINT "FK_28f8b3d42bcff4501d7a60c61d8" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" ADD CONSTRAINT "FK_726bcabc0c1a24e4c1106c0ed83" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_b0089820b7452d8e84b5d1fda65" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" ADD CONSTRAINT "FK_8a7167ed862a0600ae36cc0917c" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_9c7db4fd07371a0c1eddcd1bd20" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "debit_notes" ADD CONSTRAINT "FK_58f0559f303763439b0bf01a6b3" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "debit_notes" ADD CONSTRAINT "FK_2c1dea9ca0801e44684b492d616" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_f51acf047cb9b82ea8b0508f95a" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_a8245e923a0403ef58224a91e48" FOREIGN KEY ("ite_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_notes" ADD CONSTRAINT "FK_421ef876a7292a03a6e8dd9128e" FOREIGN KEY ("credit_note_reason_id") REFERENCES "credit_note_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_notes" ADD CONSTRAINT "FK_3b00782ddf92177eced19a05973" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_note_details" ADD CONSTRAINT "FK_2ed159ea81d2d2186c50bba8835" FOREIGN KEY ("credit_note_id") REFERENCES "credit_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_note_details" ADD CONSTRAINT "FK_fad0050b1a873a4538cae0f8fcc" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lots" ADD CONSTRAINT "FK_23237dbb26386b3ee0c0cafe4c8" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_0b51047279d22d97442d46dfee8" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_b2be25bd3e78455fe801c45e892" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movement" ADD CONSTRAINT "FK_2222849c36f2c923a4fdd19b1a8" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movement" ADD CONSTRAINT "FK_f47845a896a34a9e989ea46006a" FOREIGN KEY ("reason_id") REFERENCES "movement_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movement" ADD CONSTRAINT "FK_84dea70c36df8700e616018f256" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_b9fd3930c71019f8e356b0b2316" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_2eaaa3a5a48d27ba880826fc509" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_4b480729e659cc5db0e4998b405" FOREIGN KEY ("carrier_id") REFERENCES "carriers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_f97f75b391c6d21748430e3adbe" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guides" ADD CONSTRAINT "FK_dfcfb839bfb86f87995cd7a53ce" FOREIGN KEY ("movement_reason_id") REFERENCES "movement_reason"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guide_detail" ADD CONSTRAINT "FK_6789081fb6922aa29289e1871d6" FOREIGN KEY ("remission_guide_id") REFERENCES "remission_guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "remission_guide_detail" ADD CONSTRAINT "FK_637fa2457bd1fc924e22c422a42" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit_measurements" ADD CONSTRAINT "FK_d6e561440082736e35b7fae2886" FOREIGN KEY ("base_unit_id") REFERENCES "unit_measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_0c4aa809ddf5b0c6ca45d8a8e80" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_41612ad71ba48392ba7977103d1" FOREIGN KEY ("unit_measurement_id") REFERENCES "unit_measurements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation_detail" ADD CONSTRAINT "FK_2e22564083589c7cc4c7e5ae262" FOREIGN KEY ("purchase_liquidation_id") REFERENCES "purchase_liquidation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation_detail" ADD CONSTRAINT "FK_1ea96aa352ff937b521a23735a4" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation" ADD CONSTRAINT "FK_7965bb1da8349336a67f2f38630" FOREIGN KEY ("supplierId") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withholding_details" ADD CONSTRAINT "FK_c1edd39312aca7a5ff8a8eae4dc" FOREIGN KEY ("withholding_id") REFERENCES "withholdings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withholdings" ADD CONSTRAINT "FK_4057831c1e2230094debcd8184d" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "withholdings" ADD CONSTRAINT "FK_5d55147f054da31b8ca25caf2dc" FOREIGN KEY ("tax_id") REFERENCES "type_taxes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_1c944701a896e794276f43769a2" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_unit_measurements" ADD CONSTRAINT "FK_77b2f290c585024f3d6562eafde" FOREIGN KEY ("unit_measurement_id") REFERENCES "unit_measurements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificate" ADD CONSTRAINT "FK_e2bcee3d44b9c071afd26fe8505" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_451f765bbe21478e9ccb6aa4bdd" FOREIGN KEY ("party_id") REFERENCES "parties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_emission_points" ADD CONSTRAINT "FK_da4effb9f23e6a840c07f5e4ccc" FOREIGN KEY ("establishment_id") REFERENCES "tenant_establishments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_numbering" ADD CONSTRAINT "FK_71844eda26c6398f26621709916" FOREIGN KEY ("establishment_id") REFERENCES "tenant_establishments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_numbering" ADD CONSTRAINT "FK_14e5fbae518ecc91bf08542ccb5" FOREIGN KEY ("emission_point_id") REFERENCES "tenant_emission_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_numbering" ADD CONSTRAINT "FK_5f830f1228156f073ce1b22f8a3" FOREIGN KEY ("document_type_id") REFERENCES "document_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_890c73d7da6439aaa032cd10b9d" FOREIGN KEY ("document_type_id") REFERENCES "document_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_8f26632d75be35098ba8672c34e" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_f1af70ebdaf5d576607d811810a" FOREIGN KEY ("guide_id") REFERENCES "remission_guides"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_09296d4cf076c49709b12418bb3" FOREIGN KEY ("credit_note_id") REFERENCES "credit_notes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_f922457f05c83d5552d194407cb" FOREIGN KEY ("debit_note_id") REFERENCES "debit_notes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_00e32caeb025b72c8637e20fdda" FOREIGN KEY ("purchase_liquidation_id") REFERENCES "purchase_liquidation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" ADD CONSTRAINT "FK_bd5b8a63dd71e39b1721b336c43" FOREIGN KEY ("withholding_id") REFERENCES "withholdings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_suppliers" ADD CONSTRAINT "FK_d2f7b545014da4e5ac38c373c32" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_suppliers" ADD CONSTRAINT "FK_e2365014fdeb4fd16cf9504178d" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_suppliers" DROP CONSTRAINT "FK_e2365014fdeb4fd16cf9504178d"`);
        await queryRunner.query(`ALTER TABLE "item_suppliers" DROP CONSTRAINT "FK_d2f7b545014da4e5ac38c373c32"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_bd5b8a63dd71e39b1721b336c43"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_00e32caeb025b72c8637e20fdda"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_f922457f05c83d5552d194407cb"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_09296d4cf076c49709b12418bb3"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_f1af70ebdaf5d576607d811810a"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_8f26632d75be35098ba8672c34e"`);
        await queryRunner.query(`ALTER TABLE "electronic_documents" DROP CONSTRAINT "FK_890c73d7da6439aaa032cd10b9d"`);
        await queryRunner.query(`ALTER TABLE "tenant_numbering" DROP CONSTRAINT "FK_5f830f1228156f073ce1b22f8a3"`);
        await queryRunner.query(`ALTER TABLE "tenant_numbering" DROP CONSTRAINT "FK_14e5fbae518ecc91bf08542ccb5"`);
        await queryRunner.query(`ALTER TABLE "tenant_numbering" DROP CONSTRAINT "FK_71844eda26c6398f26621709916"`);
        await queryRunner.query(`ALTER TABLE "tenant_emission_points" DROP CONSTRAINT "FK_da4effb9f23e6a840c07f5e4ccc"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_451f765bbe21478e9ccb6aa4bdd"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "certificate" DROP CONSTRAINT "FK_e2bcee3d44b9c071afd26fe8505"`);
        await queryRunner.query(`ALTER TABLE "tenant_unit_measurements" DROP CONSTRAINT "FK_77b2f290c585024f3d6562eafde"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_1c944701a896e794276f43769a2"`);
        await queryRunner.query(`ALTER TABLE "withholdings" DROP CONSTRAINT "FK_5d55147f054da31b8ca25caf2dc"`);
        await queryRunner.query(`ALTER TABLE "withholdings" DROP CONSTRAINT "FK_4057831c1e2230094debcd8184d"`);
        await queryRunner.query(`ALTER TABLE "withholding_details" DROP CONSTRAINT "FK_c1edd39312aca7a5ff8a8eae4dc"`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation" DROP CONSTRAINT "FK_7965bb1da8349336a67f2f38630"`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation_detail" DROP CONSTRAINT "FK_1ea96aa352ff937b521a23735a4"`);
        await queryRunner.query(`ALTER TABLE "purchase_liquidation_detail" DROP CONSTRAINT "FK_2e22564083589c7cc4c7e5ae262"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_41612ad71ba48392ba7977103d1"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_0c4aa809ddf5b0c6ca45d8a8e80"`);
        await queryRunner.query(`ALTER TABLE "unit_measurements" DROP CONSTRAINT "FK_d6e561440082736e35b7fae2886"`);
        await queryRunner.query(`ALTER TABLE "remission_guide_detail" DROP CONSTRAINT "FK_637fa2457bd1fc924e22c422a42"`);
        await queryRunner.query(`ALTER TABLE "remission_guide_detail" DROP CONSTRAINT "FK_6789081fb6922aa29289e1871d6"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_dfcfb839bfb86f87995cd7a53ce"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_f97f75b391c6d21748430e3adbe"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_4b480729e659cc5db0e4998b405"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_2eaaa3a5a48d27ba880826fc509"`);
        await queryRunner.query(`ALTER TABLE "remission_guides" DROP CONSTRAINT "FK_b9fd3930c71019f8e356b0b2316"`);
        await queryRunner.query(`ALTER TABLE "stock_movement" DROP CONSTRAINT "FK_84dea70c36df8700e616018f256"`);
        await queryRunner.query(`ALTER TABLE "stock_movement" DROP CONSTRAINT "FK_f47845a896a34a9e989ea46006a"`);
        await queryRunner.query(`ALTER TABLE "stock_movement" DROP CONSTRAINT "FK_2222849c36f2c923a4fdd19b1a8"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_b2be25bd3e78455fe801c45e892"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_0b51047279d22d97442d46dfee8"`);
        await queryRunner.query(`ALTER TABLE "lots" DROP CONSTRAINT "FK_23237dbb26386b3ee0c0cafe4c8"`);
        await queryRunner.query(`ALTER TABLE "credit_note_details" DROP CONSTRAINT "FK_fad0050b1a873a4538cae0f8fcc"`);
        await queryRunner.query(`ALTER TABLE "credit_note_details" DROP CONSTRAINT "FK_2ed159ea81d2d2186c50bba8835"`);
        await queryRunner.query(`ALTER TABLE "credit_notes" DROP CONSTRAINT "FK_3b00782ddf92177eced19a05973"`);
        await queryRunner.query(`ALTER TABLE "credit_notes" DROP CONSTRAINT "FK_421ef876a7292a03a6e8dd9128e"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_a8245e923a0403ef58224a91e48"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_f51acf047cb9b82ea8b0508f95a"`);
        await queryRunner.query(`ALTER TABLE "debit_notes" DROP CONSTRAINT "FK_2c1dea9ca0801e44684b492d616"`);
        await queryRunner.query(`ALTER TABLE "debit_notes" DROP CONSTRAINT "FK_58f0559f303763439b0bf01a6b3"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_9c7db4fd07371a0c1eddcd1bd20"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_8a7167ed862a0600ae36cc0917c"`);
        await queryRunner.query(`ALTER TABLE "purchase_payments" DROP CONSTRAINT "FK_b0089820b7452d8e84b5d1fda65"`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" DROP CONSTRAINT "FK_726bcabc0c1a24e4c1106c0ed83"`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" DROP CONSTRAINT "FK_28f8b3d42bcff4501d7a60c61d8"`);
        await queryRunner.query(`ALTER TABLE "debit_note_detail" DROP CONSTRAINT "FK_a1af95ca14225263f1f4c7fe280"`);
        await queryRunner.query(`ALTER TABLE "debit_note_detail" DROP CONSTRAINT "FK_4898dbed96c8d7c4da010d706ea"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_a68cab09a94768788280c3cbf0b"`);
        await queryRunner.query(`ALTER TABLE "carriers" DROP CONSTRAINT "FK_118b02bcf80db8eb5d7982ecd67"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_4a454934d715cd3ca29ab675349"`);
        await queryRunner.query(`ALTER TABLE "tenant_taxes" DROP CONSTRAINT "FK_e555e263926898df594e1f5ffa6"`);
        await queryRunner.query(`ALTER TABLE "detail_tax_type" DROP CONSTRAINT "FK_af31f447f3c4a3bd2f908526276"`);
        await queryRunner.query(`ALTER TABLE "withholding_type_detail" DROP CONSTRAINT "FK_f29f81f93481a3f096271f1e61d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2365014fdeb4fd16cf9504178"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2f7b545014da4e5ac38c373c3"`);
        await queryRunner.query(`DROP TABLE "item_suppliers"`);
        await queryRunner.query(`DROP TABLE "electronic_documents"`);
        await queryRunner.query(`DROP TYPE "public"."electronic_documents_status_enum"`);
        await queryRunner.query(`DROP TABLE "document_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39457c1f4ecc7e8db88da581b7"`);
        await queryRunner.query(`DROP TABLE "tenant_numbering"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1545e37cd662f59dde1b762251"`);
        await queryRunner.query(`DROP TABLE "tenant_emission_points"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a4531cdccd770ff57c91cd8af"`);
        await queryRunner.query(`DROP TABLE "tenant_establishments"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_businesstype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_srienvironment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f4c2efab52114c4e99e28efb"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "certificate"`);
        await queryRunner.query(`DROP TYPE "public"."certificate_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6eb547f7f7b581208a300c5536"`);
        await queryRunner.query(`DROP TABLE "tenant_unit_measurements"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "withholdings"`);
        await queryRunner.query(`DROP TABLE "withholding_details"`);
        await queryRunner.query(`DROP TABLE "purchase_liquidation"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_liquidation_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_liquidation_detail"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4255d4e0810807dea55d9a406"`);
        await queryRunner.query(`DROP TABLE "items"`);
        await queryRunner.query(`DROP TYPE "public"."items_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93cf3893f0dd45999755aef505"`);
        await queryRunner.query(`DROP TABLE "unit_measurements"`);
        await queryRunner.query(`DROP TYPE "public"."unit_measurements_type_enum"`);
        await queryRunner.query(`DROP TABLE "remission_guide_detail"`);
        await queryRunner.query(`DROP TABLE "remission_guides"`);
        await queryRunner.query(`DROP TABLE "movement_reason"`);
        await queryRunner.query(`DROP TABLE "stock_movement"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movement_typemovement_enum"`);
        await queryRunner.query(`DROP TABLE "warehouse"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b136c68f7478c3fa49229d6f57"`);
        await queryRunner.query(`DROP TABLE "stock"`);
        await queryRunner.query(`DROP TABLE "lots"`);
        await queryRunner.query(`DROP TABLE "credit_note_details"`);
        await queryRunner.query(`DROP TABLE "credit_notes"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum"`);
        await queryRunner.query(`DROP TABLE "sale_detail"`);
        await queryRunner.query(`DROP TABLE "debit_notes"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_status_enum"`);
        await queryRunner.query(`DROP TABLE "sale_payments"`);
        await queryRunner.query(`DROP TABLE "purchase_payments"`);
        await queryRunner.query(`DROP TABLE "purchases"`);
        await queryRunner.query(`DROP TYPE "public"."purchases_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_detail"`);
        await queryRunner.query(`DROP TABLE "debit_note_detail"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "parties"`);
        await queryRunner.query(`DROP TYPE "public"."parties_partytype_enum"`);
        await queryRunner.query(`DROP TABLE "carriers"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP TYPE "public"."promotions_discounttype_enum"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`DROP TABLE "credit_note_reason"`);
        await queryRunner.query(`DROP TABLE "identification_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29ad220fc1e33ebfb74c64a9d1"`);
        await queryRunner.query(`DROP TABLE "tenant_taxes"`);
        await queryRunner.query(`DROP TABLE "type_taxes"`);
        await queryRunner.query(`DROP TABLE "detail_tax_type"`);
        await queryRunner.query(`DROP TABLE "withholding_type"`);
        await queryRunner.query(`DROP TABLE "withholding_type_detail"`);
    }

}
